### ISSUE TITLE
Faker.js should be in peer dependencies 

### ISSUE THREAD

**Issue by omer-morad-ni** [edwardanthony/nestjs-seeder#10]
Hi,

Wanted to say this a great package! You did excellent work here!

The [`"faker": "^4.1.0"`](https://github.com/edwardanthony/nestjs-seeder/blob/42435b8b4bfa3adfdb9469e428d2521825207c1b/package.json#L31) should be in the peer dependencies because you need to let the consumer determine the version of Faker.

Want me to create a PR for it?

**Comment by edwardanthony** [comment]
Hey, sorry for the late reply. I was on new year holiday.
Sure, a PR would be really helpful.
