### ISSUE TITLE
Faker version outdated

### ISSUE THREAD

**Issue by hox** [edwardanthony/nestjs-seeder#35]
Could this package be updated to allow @faker-js/faker version ^8.0.0?

**Comment by hox** [comment]
Thanks for the super fast reply!
The peer dep requires faker-js ^7.5.0, which means 8.0.0 is not allowed. 
In order for me to use it, I would have to force the version:
![image](https://github.com/edwardanthony/nestjs-seeder/assets/28278041/8e1c0a32-991d-441e-8c94-8f23dedae732)

**Comment by edwardanthony** [comment]
I'll increment the version number. I'll have to ask you to wait for me to finish the test to make sure it does not break anything.

**Comment by hox** [comment]
Thank you very much!

**Comment by edwardanthony** [comment]
Hi Elias, I've deployed a new patch version 0.3.2.
Please let me know if the new version resolves your issue. If there's nothing else, I'll close this thread.

**Comment by hox** [comment]
I have installed the new version and all is well, I appreciate your help and very fast action on this issue. You're the best!

Thanks :)

**Comment by edwardanthony** [comment]
No worries. I'd appreciate if you can leave a star in the Github repo 🙏.
