### ISSUE TITLE
Bump `faker` to `^5`

### ISSUE THREAD

**Issue by vabatta** [edwardanthony/nestjs-seeder#8]
As we can see in the `package.json`, the faker dependency is not updated to latest (`5.1.0` at time of writing). 
https://github.com/edwardanthony/nestjs-seeder/blob/master/package.json#L31

Can we bump this to `5.1.0`?

**Comment by vabatta** [comment]
@edwardanthony Just a reminder for this :)

**Comment by edwardanthony** [comment]
Hey, thank you. I was really busy. I'll bump it as soon as I can.
